# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be9dd3afcc95bf319360c587180c56800e7d7848c153700d5a1eb46b0b87dcfada157b0264ab75403ac407cec21aba9842ffe724307a59bbc5fc05128c3cacbc

test:
  secret_key_base: 63a13afe6f4b2a229b63437c7d638162bef847de39d11ba69a3829c0f066a297cace49b56f9a5e9d20b60ae8ad44404f786732333d49befee248a288a8c7c5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
